export default {
	nextLabel: '下一步',
	nextclass: '',
	prevLabel: '上一步',
	prevclass: '',
	skipLabel: '跳过',
	skipclass: '',
	doneLabel: '完成',
	doneclass: '',
	confirmtipPosition: 'bottom',
	confirmtipClass: '',
	width: '',
	height: '',
	offsetTop: '20',
	offsetLeft: '0',
}
